let DropCheker = false
let DragDropChek = false

// Generated by TypeScript
function altDump(name, object, reference) {
    $.Msg("=====================================");
    $.Msg("This is a giant dump in " + name);
    $.Msg("=====================================");
    var referenceList = [];
    for (var v in reference) {
        referenceList[v] = typeof (reference[v]);
    }
    for (var v in object) {
        if (referenceList[v] !== undefined) {
            continue;
        }
        if (typeof object[v] == "object") {
            $.Msg(v + " = {");
            for (var w in object[v]) {
                $.Msg("\t" + v + "." + w + " = " + ("" + object[v][w]));
            }
            $.Msg("}");
        }
        else {
            $.Msg(name + "." + v + " = (" + typeof object[v] + ") " + object[v]);
        }
    }
    $.Msg("=====================================");
}
var ItemState;
(function (ItemState) {
    ItemState[ItemState["Default"] = 0] = "Default";
    ItemState[ItemState["Active"] = 1] = "Active";
    ItemState[ItemState["AbilityPhase"] = 2] = "AbilityPhase";
    ItemState[ItemState["Cooldown"] = 3] = "Cooldown";
    ItemState[ItemState["Muted"] = 4] = "Muted";
})(ItemState || (ItemState = {}));
var ItemPanel = (function () {
    function ItemPanel(parent, slot) {
        this.keybind = "";
        this.slot = slot;
        // this.DropItemAtCursorFun = function name(params) {
        //     var itemID = draggedPanel.GetAttributeInt("itemID", -1);
        //         var unitID = draggedPanel.GetAttributeInt("unitID", -1);
        //         Game.DropItemAtCursor(unitID, itemID);
        // };
        this.panel = $.CreatePanel("Panel", parent, "");
        this.panel.BLoadLayoutSnippet("itemSlot");
        this.panel.SetPanelEvent("onmouseover", this.onMouseOver.bind(this));
        this.panel.SetPanelEvent("onmouseout", this.onMouseOut.bind(this));
        this.panel.SetPanelEvent("oncontextmenu", this.onRightClick.bind(this));
		this.panel.SetPanelEvent("onactivate", this.onLeftClick.bind(this));
        $.RegisterEventHandler("DragStart", this.panel, this.onDragStart.bind(this));
        $.RegisterEventHandler("DragEnd", this.panel, this.onDragEnd.bind(this));
        $.RegisterEventHandler("DragDrop", this.panel, this.onDragDrop.bind(this));
        this.update();
    }
    ItemPanel.prototype.onMouseOver = function () {
        if (this.item == -1)
            return;
        $.DispatchEvent("DOTAShowAbilityInventoryItemTooltip", this.panel, this.unit, this.slot);
    };
    ItemPanel.prototype.onMouseOut = function () {
        $.DispatchEvent("DOTAHideAbilityTooltip", this.panel);
    };
    ItemPanel.prototype.onRightClick = function () {
        var panel = $.CreatePanel("ContextMenuScript", this.panel, "");
        panel.AddClass("ContextMenu_NoArrow");
        panel.AddClass("ContextMenu_NoBorder");
        panel.GetContentsPanel().BLoadLayout("file://{resources}/layout/custom_game/inventory/itemslot_contextmenu.xml", false, false);
        panel.GetContentsPanel().SetHasClass("NotInShop", !Items.IsPurchasable(this.item));
        panel.GetContentsPanel().SetHasClass("Unsellable", !Items.IsSellable(this.item));
        panel.GetContentsPanel().SetHasClass("UnDisassemblable", !Items.IsDisassemblable(this.item));
        panel.GetContentsPanel().SetHasClass("UnAlertable", !Items.IsAlertableItem(this.item));
        panel.GetContentsPanel().SetHasClass("NotInStash", this.slot < 6);
        panel.GetContentsPanel().SetHasClass("UnStashable", !Items.IsDroppable(this.item) || !Entities.IsInRangeOfShop(this.unit, 0, true));
        //TODO: LOCKED / UNLOCKED VALVE PLZ
        panel.GetContentsPanel().SetAttributeInt("itemID", this.item);
        altDump("ContextMenu", panel, this.panel);
    };
	ItemPanel.prototype.onLeftClick = function () {
        Abilities.ExecuteAbility(this.item, this.unit, false);
    };
    ItemPanel.prototype.onDragStart = function (panelID, dragCallbacks) {
        DragDropChek = false

        if (this.item == -1) {
            return true;
        }
        var panel = $.CreatePanel("Image", this.panel, "dragImage");
        panel.SetAttributeInt("itemID", this.item);
        panel.SetAttributeInt("unitID", this.unit);
        panel.SetImage("s2r://panorama/images/items/" + Items.GetAbilityTextureSF(this.item) + ".png");
        dragCallbacks.displayPanel = panel;
        dragCallbacks.offsetX = 0;
        dragCallbacks.offsetY = 0;
        return true;
    };
    ItemPanel.prototype.onDragDrop = function (panelID, draggedPanel) {
        DragDropChek = true
        
        if (panelID.id == 'hover') {
            DropCheker = true
        } else {
            DropCheker = false
        }
        if (draggedPanel.GetAttributeInt("itemID", -1) == this.item) {
            return true;
        }
        Game.PrepareUnitOrders({
            OrderType: dotaunitorder_t.DOTA_UNIT_ORDER_MOVE_ITEM,
            TargetIndex: this.slot,
            AbilityIndex: draggedPanel.GetAttributeInt("itemID", -1)
        });
        return true;
    };
    ItemPanel.prototype.onDragEnd = function (panelID, draggedPanel) {
        $.Schedule( 0, function () {
        var isSwapping = draggedPanel.GetAttributeInt("swapping", 0);
        if (!isSwapping) {
            var itemID = draggedPanel.GetAttributeInt("itemID", -1);
            var unitID = draggedPanel.GetAttributeInt("unitID", -1);
                if (DragDropChek == false & DropCheker == false) {
                    Game.DropItemAtCursor(unitID, itemID);
                }
        }
        draggedPanel.DeleteAsync(0);
        DropCheker = false
        return true;
        } )
    };
    ItemPanel.prototype.update = function () {
        this.unit = Players.GetQueryUnit(Players.GetLocalPlayer());
        if (this.unit === -1) {
            this.unit = Players.GetLocalPlayerPortraitUnit();
        }
        this.item = Entities.GetItemInSlot(this.unit, this.slot);
        this.itemName = Abilities.GetAbilityName(this.item);
        if (this.keybind == "") {
            this.keybind = Abilities.GetKeybind(this.item);
            this.panel.FindChildTraverse("hotkey").text = this.keybind;
        }
        this.panel.SetHasClass("Muted", Items.IsMuted(this.item));
        this.panel.SetHasClass("Primary", Items.ShouldDisplayCharges(this.item));
        this.panel.SetHasClass("Secondary", Items.ShowSecondaryCharges(this.item));
        //Due to the native of inverting IsPassive, need to do empty checks first.
        if (this.item == -1) {
            this.panel.RemoveClass("Active");
        }
        else {
            this.panel.SetHasClass("Active", !Abilities.IsPassive(this.item));
        }
        //WTF Valve, why not just have secondary being secondary and primary being primary!
        if (Abilities.GetToggleState(this.item) || !Items.ShowSecondaryCharges(this.item)) {
            this.panel.FindChildTraverse("primary").text = Items.GetDisplayedCharges(this.item).toString();
            this.panel.FindChildTraverse("secondary").text = Items.GetSecondaryCharges(this.item).toString();
        }
        else {
            this.panel.FindChildTraverse("secondary").text = Items.GetDisplayedCharges(this.item).toString();
            this.panel.FindChildTraverse("primary").text = Items.GetSecondaryCharges(this.item).toString();
        }
        var itemImage = this.panel.FindChildTraverse("bg");
        itemImage.SetImage("s2r://panorama/images/items/" + ((this.item == -1) ? "emptyitembg" : Items.GetAbilityTextureSF(this.item)) + ".png");
    };
    return ItemPanel;
}());